# Copyright 2025 Xiaomi Corporation.

dataset_path: lscpku/DynaMath_Sample
dataset_kwargs:
  token: True
task: "dynamath_test"
test_split: sample_variant1
output_type: generate_until
doc_to_visual: !function utils.dynamath_doc_to_visual
doc_to_text: !function utils.dynamath_doc_to_text
doc_to_target: "ground_truth"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.dynamath_process_results
metric_list:
  - metric: dynamath_standard_eval
    aggregation: !function utils.dynamath_aggregate_results
    higher_is_better: True
  - metric: dynamath_worst_case_acc
    aggregation: !function utils.dynamath_aggregate_results_worst_case_acc
    higher_is_better: True
