# Copyright 2025 Xiaomi Corporation.
group: screenspot_pro_en_reg
task: screenspot_pro_en_reg_test
test_split: test
dataset_path: lscpku/ScreenSpot-Pro
output_type: generate_until
doc_to_visual: !function utils.screenspot_bbox_doc_to_visual
doc_to_text: !function utils.screenspot_pro_en_doc_to_text
doc_to_target: "instruction"
generation_kwargs:
  temperature: 0.0
  max_new_tokens: 32768
process_results: !function utils.screenspot_pro_en_process_result
metric_list:
  - metric: screenspot_CIDEr
    aggregation : !function utils.screenspot_cider
    higher_is_better : true
metadata:
  version: '0.0'