# Copyright 2025 Xiaomi Corporation.

group: visualwebbench
task:
- visualwebbench_action_ground
- visualwebbench_action_prediction
- visualwebbench_element_ground
- visualwebbench_element_ocr
- visualwebbench_heading_ocr
- visualwebbench_web_caption
- visualwebbench_webqa